# -*- coding: utf-8 -*-
"""Assignment2_JRCAI.ipynb 

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYQg0Ksz4R2x6vFj5z_LHWz5FAxEjwzR

##Assignment 2_JRCAI: Customer Purchase Dataset

**Prepared by:** Madawi Alshebil  
**Email:** Madawi.alshebil@gmail.com  
**Supervisor:** Dr. Safwan Al-Selwi  
**Email:** saf1.alselwi@gmail.com
"""

import pandas as pd

# Read the CSV file
df = pd.read_csv("customer_purchase_dataset.csv")

# View the entire dataset
display(df)

print("Dataset shape:", df.shape)

print("\nColumn information:")
df.info()

"""##1. Data Preprocessing

"""

# Counting missing values in every column
print("Missing values in each column:")
print(df.isnull().sum())

# Counting duplicated rows
print("\nNumber of duplicated rows:")
print(df.duplicated().sum())

# Checking for impossible/ Negative Age values

invalid_age = df[(df["Age"] < 0) | (df["Age"] > 120)]
invalid_income = df[df["Income"] < 0]

display(invalid_age)
display(invalid_income)

# Checking categorical values for spelling inconsistencies

print(df["Gender"].unique())

print(df["ProductCategory"].unique())

print(df["Purchased"].unique())

# Cleaning the dataset


df_clean = df.copy() # Creating a cleaned copy of the dataset

df_clean["Age"] = df_clean["Age"].fillna(round(df_clean["Age"].mean())).astype(int)

df_clean["Income"] = df_clean["Income"].fillna(round(df_clean["Income"].mean())).astype(int)

display(df_clean)

# Encoding the categorical variables

df_encoded = df_clean.copy()

df_encoded["Gender"] = df_encoded["Gender"].map({"Female": 0,"Male": 1})

df_encoded["Purchased"] = df_encoded["Purchased"].map({"No": 0,"Yes": 1})

df_encoded = pd.get_dummies(df_encoded,columns=["ProductCategory"],dtype=int)

display(df_encoded)

# Applying MinMaxScalar to Age and Income

from sklearn.preprocessing import MinMaxScaler

df_scaled = df_encoded.copy()
scaler = MinMaxScaler()

df_scaled[["Age", "Income"]] = scaler.fit_transform(df_scaled[["Age", "Income"]])

print("Final Cleaned and Scaled Dataset:")
display(df_scaled.round(3))

"""## 2. Basic Analysis"""

# Calculating the mean of Age and Income
print(f"Mean Age: {df_encoded['Age'].mean():.2f}")
print(f"Mean Income: {df_encoded['Income'].mean():,.2f}")

# Creating histograms

import matplotlib.pyplot as plt

plt.hist(df_encoded["Age"], bins=6, edgecolor="black")
plt.title("Distribution of Customer Age")
plt.xlabel("Age")
plt.ylabel("Number of Customers")
plt.show()

plt.hist(df_encoded["Income"], bins=6, edgecolor="black")
plt.title("Distribution of Customer Income")
plt.xlabel("Annual Income")
plt.ylabel("Number of Customers")
plt.show()

"""## 3. Modeling"""

# Preparing the model variables

X = df_encoded.drop(columns=["CustomerID", "Purchased"]) #input variables

y = df_encoded["Purchased"] #target variable

# Creating the Decision Tree model
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=1,random_state=42)

X

y

"""## 4. Evaluation"""

# Using five-fold cross-validation to test the model and displaying the accuracy
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import accuracy_score

# Create five-fold cross-validation
cv = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

# Generate predictions
predictions = cross_val_predict(model,X,y,cv=cv)

# Calculate accuracy
accuracy = accuracy_score(y, predictions)

print(f"Decision Tree Accuracy: {accuracy * 100:.2f}%")

# Calculating the accuracy after scaling

X_scaled = df_scaled.drop(columns=["CustomerID", "Purchased"])

scaled_predictions = cross_val_predict(model,X_scaled,y,cv=cv)

scaled_accuracy = accuracy_score(y, scaled_predictions)

# Compare accuracy before and after scaling
accuracy_comparison = pd.DataFrame({
    "Model": ["Before Scaling","After MinMax Scaling"],"Accuracy": [f"{accuracy * 100:.2f}%",f"{scaled_accuracy * 100:.2f}%"]})

display(accuracy_comparison)

# Decision tree visualization

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

# Train the model on the complete dataset for visualization
model.fit(X, y)

plt.figure(figsize=(12, 6))

plot_tree(model,feature_names=X.columns,class_names=["No", "Yes"],filled=True,rounded=True,fontsize=11)

plt.title("Decision Tree for Customer Purchase Prediction")
plt.show()

# Training and visualizing the final scaled model

# Train the final Decision Tree using the already scaled dataset
final_scaled_model = DecisionTreeClassifier(max_depth=1,random_state=42)

final_scaled_model.fit(X_scaled, y)

# Visualize the final Decision Tree
plt.figure(figsize=(12, 6))

plot_tree(
    final_scaled_model,
    feature_names=X_scaled.columns,
    class_names=["No", "Yes"],
    filled=True,
    rounded=True,
    fontsize=11)

plt.title("Decision Tree After MinMax Scaling")
plt.show()
