# -*- coding: utf-8 -*-
"""Phase2_ML_Model_Development.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e1g7I0ZPG3xGyZrU8ycGuq4VuE8G5hwm

# Phase 2 Project — Machine Learning Model Development


**Prepared by:** Madawi Alshebil  
**Email:** Madawi.alshebil@gmail.com  
**Supervisor:** Dr. Safwan Al-Selwi  
**Email:** saf1.alselwi@gmail.com

This project develops three end-to-end Scikit-learn pipelines:

1. **Regression:** Diabetes disease-progression prediction  
2. **Binary classification:** Breast-cancer malignancy prediction  
3. **Clustering:** Iris flower grouping using K-Means  

The notebook covers data inspection, preprocessing, EDA, model comparison,
evaluation, and final model selection.

## 1. Imports and configuration
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.base import clone
from sklearn.datasets import load_diabetes, load_breast_cancer, load_iris
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.svm import SVR, SVC
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.cluster import KMeans

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    silhouette_score
)

RANDOM_STATE = 42
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda value: f"{value:.4f}")

"""## 2. Helper functions

These functions reduce repeated code and keep the notebook organized.

"""

def iqr_outlier_counts(dataframe):
    """Return the number of IQR outliers in every numerical column."""
    counts = {}
    for column in dataframe.select_dtypes(include=np.number).columns:
        q1 = dataframe[column].quantile(0.25)
        q3 = dataframe[column].quantile(0.75)
        iqr = q3 - q1
        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr
        counts[column] = int(
            ((dataframe[column] < lower) | (dataframe[column] > upper)).sum()
        )
    return pd.Series(counts, name="IQR Outlier Count").sort_values(ascending=False)


def regression_metrics(y_true, y_pred):
    """Calculate the main regression evaluation metrics."""
    return {
        "MAE": mean_absolute_error(y_true, y_pred),
        "RMSE": np.sqrt(mean_squared_error(y_true, y_pred)),
        "R2": r2_score(y_true, y_pred)
    }


def classification_metrics(y_true, y_pred, y_score):
    """Calculate binary-classification metrics for the positive class."""
    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1": f1_score(y_true, y_pred, zero_division=0),
        "ROC_AUC": roc_auc_score(y_true, y_score)
    }


def get_positive_scores(model, X):
    """Return positive-class scores for ROC-AUC and ROC curves."""
    if hasattr(model, "predict_proba"):
        return model.predict_proba(X)[:, 1]
    return model.decision_function(X)


def plot_confusion_matrix(cm, class_names, title):
    """Display a confusion matrix using Matplotlib only."""
    fig, ax = plt.subplots(figsize=(5, 4))
    image = ax.imshow(cm)
    ax.set_title(title)
    ax.set_xlabel("Predicted Label")
    ax.set_ylabel("True Label")
    ax.set_xticks(range(len(class_names)))
    ax.set_yticks(range(len(class_names)))
    ax.set_xticklabels(class_names)
    ax.set_yticklabels(class_names)

    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, cm[i, j], ha="center", va="center")

    fig.colorbar(image, ax=ax)
    plt.tight_layout()
    plt.show()

"""# Part A — Regression Pipeline

## 3. Load the Diabetes dataset

The target is a continuous measure of disease progression one year after baseline, so this is a regression task.

"""

diabetes = load_diabetes(as_frame=True)

X_reg = diabetes.data.copy()
y_reg = diabetes.target.copy()
regression_df = X_reg.copy()
regression_df["target"] = y_reg

print("Dataset shape:", regression_df.shape)
print("\nFirst five rows:")
display(regression_df.head())

print("\nFeature names:")
print(list(X_reg.columns))

print("\nTarget description:")
display(y_reg.describe().to_frame("target"))

"""## 4. Regression data-quality checks and EDA"""

print("Missing values:")
display(regression_df.isnull().sum().to_frame("Missing Values"))

print("Number of duplicate rows:", regression_df.duplicated().sum())

print("\nIQR outlier counts:")
display(iqr_outlier_counts(regression_df).to_frame())

print(
    "\nDecision: The dataset has no missing values. "
    "Potential outliers are retained because they may represent valid patients, "
    "and tree-based models are also included in the comparison."
)

plt.figure(figsize=(7, 4))
plt.hist(y_reg, bins=20, edgecolor="black")
plt.title("Distribution of Diabetes Disease-Progression Target")
plt.xlabel("Target Value")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

correlations = regression_df.corr(numeric_only=True)["target"].drop("target")
correlations = correlations.sort_values()

plt.figure(figsize=(8, 5))
plt.barh(correlations.index, correlations.values)
plt.title("Feature Correlation with the Regression Target")
plt.xlabel("Correlation")
plt.tight_layout()
plt.show()

"""## 5. Train, validation, and test split

The data is divided into:

- **60% training:** fit the candidate models;
- **20% validation:** compare and select the best model;
- **20% testing:** report the final unbiased performance.

"""

X_reg_train_full, X_reg_test, y_reg_train_full, y_reg_test = train_test_split(
    X_reg,
    y_reg,
    test_size=0.20,
    random_state=RANDOM_STATE
)

X_reg_train, X_reg_val, y_reg_train, y_reg_val = train_test_split(
    X_reg_train_full,
    y_reg_train_full,
    test_size=0.25,
    random_state=RANDOM_STATE
)

print("Training samples:", len(X_reg_train))
print("Validation samples:", len(X_reg_val))
print("Test samples:", len(X_reg_test))

"""## 6. Regression model comparison

Scaling is included inside pipelines for Linear Regression, SVR, and KNN.  
Decision Tree and Random Forest are not scaled because tree models do not depend on feature distance.

"""

regression_models = {
    "Linear Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LinearRegression())
    ]),
    "Decision Tree": DecisionTreeRegressor(
        max_depth=5,
        min_samples_leaf=5,
        random_state=RANDOM_STATE
    ),
    "Random Forest": RandomForestRegressor(
        n_estimators=200,
        min_samples_leaf=2,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),
    "Support Vector Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVR(C=10, kernel="rbf", epsilon=0.1))
    ]),
    "K-Nearest Neighbors": Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsRegressor(
            n_neighbors=7,
            weights="distance"
        ))
    ])
}

regression_rows = []

for model_name, model in regression_models.items():
    fitted_model = clone(model)
    fitted_model.fit(X_reg_train, y_reg_train)
    train_predictions = fitted_model.predict(X_reg_train)
    validation_predictions = fitted_model.predict(X_reg_val)

    train_results = regression_metrics(y_reg_train, train_predictions)
    validation_results = regression_metrics(y_reg_val, validation_predictions)

    regression_rows.append({
        "Model": model_name,
        "Train_RMSE": train_results["RMSE"],
        "Validation_MAE": validation_results["MAE"],
        "Validation_RMSE": validation_results["RMSE"],
        "Validation_R2": validation_results["R2"],
        "RMSE_Gap": validation_results["RMSE"] - train_results["RMSE"]
    })


regression_results = (
    pd.DataFrame(regression_rows)
    .sort_values("Validation_RMSE")
    .reset_index(drop=True)
)

display(regression_results)

plt.figure(figsize=(9, 5))
plt.bar(
    regression_results["Model"],
    regression_results["Validation_RMSE"]
)
plt.title("Regression Model Comparison — Validation RMSE")
plt.ylabel("RMSE (Lower Is Better)")
plt.xticks(rotation=25, ha="right")
plt.tight_layout()
plt.show()

print(
    "The Train_RMSE, Validation_RMSE, and RMSE_Gap columns in the table "
    "are used to check possible overfitting and generalization."
)

"""## 7. Select and test the best regression model

The selected model is the one with the **lowest validation RMSE**.  
It is retrained using the combined training and validation data, then evaluated once on the untouched test set.

"""

best_regression_name = regression_results.iloc[0]["Model"]
best_regression_model = clone(regression_models[best_regression_name])

best_regression_model.fit(X_reg_train_full, y_reg_train_full)
regression_test_predictions = best_regression_model.predict(X_reg_test)

regression_test_results = regression_metrics(
    y_reg_test,
    regression_test_predictions
)

print("Selected regression model:", best_regression_name)
print("\nFinal test metrics:")
display(pd.DataFrame([regression_test_results]))

plt.figure(figsize=(6, 6))
plt.scatter(y_reg_test, regression_test_predictions)

minimum = min(y_reg_test.min(), regression_test_predictions.min())
maximum = max(y_reg_test.max(), regression_test_predictions.max())

plt.plot(
    [minimum, maximum],
    [minimum, maximum],
    linestyle="--"
)

plt.title(f"Actual vs Predicted — {best_regression_name}")
plt.xlabel("Actual Target")
plt.ylabel("Predicted Target")
plt.tight_layout()
plt.show()

"""# Part B — Binary Classification Pipeline

## 8. Load the Breast Cancer Wisconsin dataset

The target is remapped so that:

- `1 = Malignant` — positive class  
- `0 = Benign` — negative class  

This makes recall easy to interpret: malignant recall measures how many malignant cases the model successfully detects.

"""

cancer = load_breast_cancer(as_frame=True)

X_cls = cancer.data.copy()
y_cls = (cancer.target == 0).astype(int)
y_cls.name = "malignant"

classification_df = X_cls.copy()
classification_df["malignant"] = y_cls

print("Dataset shape:", classification_df.shape)
print("\nFirst five rows:")
display(classification_df.head())

print("\nClass mapping:")
print("0 = Benign")
print("1 = Malignant")

"""## 9. Classification data-quality checks and EDA"""

print("Missing values:", int(classification_df.isnull().sum().sum()))
print("Duplicate rows:", int(classification_df.duplicated().sum()))

class_counts = y_cls.value_counts().sort_index()
class_distribution = pd.DataFrame({
    "Class": ["Benign", "Malignant"],
    "Count": [class_counts.get(0, 0), class_counts.get(1, 0)]
})
display(class_distribution)

plt.figure(figsize=(6, 4))
plt.bar(class_distribution["Class"], class_distribution["Count"])
plt.title("Breast Cancer Class Distribution")
plt.ylabel("Number of Samples")
plt.tight_layout()
plt.show()

print("\nTop IQR outlier counts:")
display(iqr_outlier_counts(X_cls).head(10).to_frame())

print(
    "\nDecision: No missing values are present. "
    "Potential outliers are retained because they may be clinically meaningful. "
    "Standardization is applied to distance- and margin-based models."
)

"""## 10. Stratified train, validation, and test split"""

X_cls_train_full, X_cls_test, y_cls_train_full, y_cls_test = train_test_split(
    X_cls,
    y_cls,
    test_size=0.20,
    random_state=RANDOM_STATE,
    stratify=y_cls
)

X_cls_train, X_cls_val, y_cls_train, y_cls_val = train_test_split(
    X_cls_train_full,
    y_cls_train_full,
    test_size=0.25,
    random_state=RANDOM_STATE,
    stratify=y_cls_train_full
)

print("Training samples:", len(X_cls_train))
print("Validation samples:", len(X_cls_val))
print("Test samples:", len(X_cls_test))

print("\nMalignant proportion:")
print("Training:", y_cls_train.mean())
print("Validation:", y_cls_val.mean())
print("Test:", y_cls_test.mean())

"""## 11. Classification model comparison

The models are evaluated using:

- Accuracy
- Precision
- Recall
- F1-score
- ROC-AUC

Because the positive class is **malignant**, recall is especially important: a false negative means a malignant case was incorrectly predicted as benign.

"""

classification_models = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(
            max_iter=2000,
            class_weight="balanced",
            random_state=RANDOM_STATE
        ))
    ]),
    "Decision Tree": DecisionTreeClassifier(
        max_depth=4,
        min_samples_leaf=5,
        class_weight="balanced",
        random_state=RANDOM_STATE
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=RANDOM_STATE,
        n_jobs=-1
    ),
    "Support Vector Machine": Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVC(
            C=2,
            kernel="rbf",
            probability=True,
            class_weight="balanced",
            random_state=RANDOM_STATE
        ))
    ]),
    "K-Nearest Neighbors": Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsClassifier(
            n_neighbors=7,
            weights="distance"
        ))
    ]),
    "Naive Bayes": GaussianNB()
}

classification_rows = []

for model_name, model in classification_models.items():
    fitted_model = clone(model)
    fitted_model.fit(X_cls_train, y_cls_train)

    train_predictions = fitted_model.predict(X_cls_train)
    validation_predictions = fitted_model.predict(X_cls_val)
    validation_scores = get_positive_scores(fitted_model, X_cls_val)

    validation_results = classification_metrics(
        y_cls_val,
        validation_predictions,
        validation_scores
    )

    classification_rows.append({
        "Model": model_name,
        "Train_Accuracy": accuracy_score(y_cls_train, train_predictions),
        "Validation_Accuracy": validation_results["Accuracy"],
        "Validation_Precision": validation_results["Precision"],
        "Validation_Recall": validation_results["Recall"],
        "Validation_F1": validation_results["F1"],
        "Validation_ROC_AUC": validation_results["ROC_AUC"],
        "Accuracy_Gap": (
            accuracy_score(y_cls_train, train_predictions)
            - validation_results["Accuracy"]
        )
    })


classification_results = (
    pd.DataFrame(classification_rows)
    .sort_values(
        ["Validation_Recall", "Validation_F1", "Validation_ROC_AUC"],
        ascending=False
    )
    .reset_index(drop=True)
)

display(classification_results)

plt.figure(figsize=(10, 5))
plt.bar(
    classification_results["Model"],
    classification_results["Validation_Recall"]
)
plt.title("Classification Model Comparison — Malignant Recall")
plt.ylabel("Recall (Higher Is Better)")
plt.ylim(0, 1.05)
plt.xticks(rotation=25, ha="right")
plt.tight_layout()
plt.show()

print(
    "ROC-AUC values are included in the comparison table, "
    "so a separate ROC-curve graph is not required here."
)

"""## 12. Select and test the best classification model

Selection rule:

1. highest validation recall;
2. if tied, highest validation F1-score;
3. if still tied, highest validation ROC-AUC.

This rule prioritizes detection of malignant cases.

"""

best_classification_name = classification_results.iloc[0]["Model"]
best_classification_model = clone(
    classification_models[best_classification_name]
)

best_classification_model.fit(
    X_cls_train_full,
    y_cls_train_full
)

classification_test_predictions = best_classification_model.predict(
    X_cls_test
)
classification_test_scores = get_positive_scores(
    best_classification_model,
    X_cls_test
)

classification_test_results = classification_metrics(
    y_cls_test,
    classification_test_predictions,
    classification_test_scores
)

print("Selected classification model:", best_classification_name)
print("\nFinal test metrics:")
display(pd.DataFrame([classification_test_results]))

print("\nClassification report:")
print(
    classification_report(
        y_cls_test,
        classification_test_predictions,
        target_names=["Benign", "Malignant"],
        digits=4
    )
)

test_cm = confusion_matrix(
    y_cls_test,
    classification_test_predictions
)
plot_confusion_matrix(
    test_cm,
    ["Benign", "Malignant"],
    f"Test Confusion Matrix — {best_classification_name}"
)

"""## 13. Classification error interpretation

For the confusion matrix:

- **True Negative:** benign correctly predicted as benign;
- **False Positive:** benign incorrectly predicted as malignant;
- **False Negative:** malignant incorrectly predicted as benign;
- **True Positive:** malignant correctly predicted as malignant.

In this problem, false negatives are particularly important because they represent missed malignant cases.

> This project is an educational demonstration and is not a clinical diagnostic system.

# Part C — Clustering Pipeline

## 14. Load the Iris dataset

K-Means is trained using only the four numerical flower measurements.  
The original species labels are not used during clustering.
"""

iris = load_iris(as_frame=True)

X_cluster = iris.data.copy()
iris_labels_for_reference = iris.target.copy()

print("Dataset shape:", X_cluster.shape)
print("\nFirst five rows:")
display(X_cluster.head())

print("\nMissing values:", int(X_cluster.isnull().sum().sum()))
print("Duplicate rows:", int(X_cluster.duplicated().sum()))

"""## 15. Clustering EDA and preprocessing

K-Means depends on distance, so the features are standardized before clustering.  
PCA is used only to create a two-dimensional visualization.

"""

display(X_cluster.describe().T)

cluster_scaler = StandardScaler()
X_cluster_scaled = cluster_scaler.fit_transform(X_cluster)

pca = PCA(n_components=2, random_state=RANDOM_STATE)
X_cluster_pca = pca.fit_transform(X_cluster_scaled)

print(
    "Variance explained by the first two principal components:",
    f"{pca.explained_variance_ratio_.sum():.2%}"
)

"""## 16. Select the number of clusters

K-Means is tested with `K = 2` through `K = 6`.

- **Inertia:** lower values indicate tighter clusters, but inertia always decreases as K increases.
- **Silhouette score:** higher values indicate better separation and cohesion.

The final K is selected using the highest silhouette score.

"""

kmeans_rows = []

for k in range(2, 7):
    model = KMeans(
        n_clusters=k,
        n_init=20,
        random_state=RANDOM_STATE
    )

    cluster_assignments = model.fit_predict(X_cluster_scaled)

    kmeans_rows.append({
        "K": k,
        "Inertia": model.inertia_,
        "Silhouette_Score": silhouette_score(
            X_cluster_scaled,
            cluster_assignments
        )
    })

kmeans_results = pd.DataFrame(kmeans_rows)
display(kmeans_results)

plt.figure(figsize=(7, 4))
plt.plot(
    kmeans_results["K"],
    kmeans_results["Silhouette_Score"],
    marker="o"
)
plt.title("K-Means Silhouette Analysis")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Silhouette Score")
plt.xticks(kmeans_results["K"])
plt.tight_layout()
plt.show()

"""## 17. Final K-Means model and cluster interpretation"""

best_k = int(
    kmeans_results.loc[
        kmeans_results["Silhouette_Score"].idxmax(),
        "K"
    ]
)

best_kmeans = KMeans(
    n_clusters=best_k,
    n_init=20,
    random_state=RANDOM_STATE
)

final_clusters = best_kmeans.fit_predict(X_cluster_scaled)

print("Selected number of clusters:", best_k)

plt.figure(figsize=(8, 6))

for cluster_number in range(best_k):
    mask = final_clusters == cluster_number

    plt.scatter(
        X_cluster_pca[mask, 0],
        X_cluster_pca[mask, 1],
        label=f"Cluster {cluster_number + 1}"
    )

centroids_pca = pca.transform(best_kmeans.cluster_centers_)

plt.scatter(
    centroids_pca[:, 0],
    centroids_pca[:, 1],
    marker="X",
    s=250,
    edgecolors="black",
    label="Centroids"
)

plt.title(f"K-Means Clustering of Iris Data (K={best_k})")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend()
plt.tight_layout()
plt.show()

cluster_profile = (
    X_cluster.assign(Cluster=final_clusters + 1)
    .groupby("Cluster")
    .mean()
    .round(3)
)

display(cluster_profile)

"""# 18. Final project summary and conclusions

"""

final_summary = pd.DataFrame([
    {
        "Paradigm": "Regression",
        "Dataset": "Diabetes",
        "Selected Model": best_regression_name,
        "Selection Metric": "Lowest validation RMSE",
        "Final Test Result": (
            f"RMSE={regression_test_results['RMSE']:.4f}, "
            f"MAE={regression_test_results['MAE']:.4f}, "
            f"R2={regression_test_results['R2']:.4f}"
        )
    },
    {
        "Paradigm": "Binary Classification",
        "Dataset": "Breast Cancer Wisconsin",
        "Selected Model": best_classification_name,
        "Selection Metric": "Recall, then F1, then ROC-AUC",
        "Final Test Result": (
            f"Recall={classification_test_results['Recall']:.4f}, "
            f"F1={classification_test_results['F1']:.4f}, "
            f"ROC-AUC={classification_test_results['ROC_AUC']:.4f}"
        )
    },
    {
        "Paradigm": "Clustering",
        "Dataset": "Iris",
        "Selected Model": f"K-Means (K={best_k})",
        "Selection Metric": "Highest silhouette score",
        "Final Test Result": (
            f"Silhouette="
            f"{kmeans_results.loc[kmeans_results['K'] == best_k, 'Silhouette_Score'].iloc[0]:.4f}"
        )
    }
])

display(final_summary)

"""## Main findings

- Regression models were compared using validation MAE, RMSE, and R².
- Classification models were compared using Accuracy, Precision, Recall, F1-score, and ROC-AUC.
- Train-versus-validation results were used to check generalization.
- K-Means was evaluated using inertia and silhouette score.

"""